### ISSUE TITLE
I can't download the file d.pth

### ISSUE THREAD

**Issue by OmlineEditor** [LeslieZhoa/GFPGAN-1024#3]
your instructions say:

...
7. get discriminator [here](https://github.com/LeslieZhoa/GFPGAN-1024/releases/download/untagged-7fadd91b517da1810e55/d.pth) which is transformed from original stylegan2
...

I can't download the file: d.pth   (404 error)
fix the link

**Comment by danial880** [comment]
Please, fix the link

**Comment by OmlineEditor** [comment]
That's it, I downloaded it. please correct the link in the description

**Comment by ningbende** [comment]
> Please, fix the link. Can you confirm that GFPGANv1_net_d.pth [here](https://drive.google.com/drive/folders/17rLiFzcUMoQuhLnptDsKolegHWwJOnHu) is the same model described as d.pth?

I used  this file，but I found this error：

  File "/root/dirac/GFPGAN-1024/trainer/GFPTrainer.py", line 451, in load_scratch
    self.netD.load_state_dict(torch.load(self.args.scratch_d_path))
  File "/root/miniconda3/envs/py38torch18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for StyleGAN2Discriminator:
        Missing key(s) in state_dict: "conv_body.0.0.weight", "conv_body.0.1.bias", "conv_body.1.conv1.0.weight", "conv_body.1.conv1.1.bias", "conv_body.1.conv2.1.weight", "conv_body.1.conv2.2.bias", "conv_body.1.skip.1.weight", "conv_body.2.conv1.0.weight", "conv_body.2.conv1.1.bias", "conv_body.2.conv2.1.weight", "conv_body.2.conv2.2.bias", "conv_body.2.skip.1.weight", "conv_body.3.conv1.0.weight", "conv_body.3.conv1.1.bias", "conv_body.3.conv2.1.weight", "conv_body.3.conv2.2.bias", "conv_body.3.skip.1.weight", "conv_body.4.conv1.0.weight", "conv_body.4.conv1.1.bias", "conv_body.4.conv2.1.weight", "conv_body.4.conv2.2.bias", "conv_body.4.skip.1.weight", "conv_body.5.conv1.0.weight", "conv_body.5.conv1.1.bias", "conv_body.5.conv2.1.weight", "conv_body.5.conv2.2.bias", "conv_body.5.skip.1.weight", "conv_body.6.conv1.0.weight", "conv_body.6.conv1.1.bias", "conv_body.6.conv2.1.weight", "conv_body.6.conv2.2.bias", "conv_body.6.skip.1.weight", "conv_body.7.conv1.0.weight", "conv_body.7.conv1.1.bias", "conv_body.7.conv2.1.weight", "conv_body.7.conv2.2.bias", "conv_body.7.skip.1.weight", "final_conv.0.weight", "final_conv.1.bias", "final_linear.0.weight", "final_linear.0.bias", "final_linear.1.weight", "final_linear.1.bias".
        Unexpected key(s) in state_dict: "params".

**Comment by luser350** [comment]
GFPTrainer.py", line 451
self.netD.load_state_dict(torch.load(self.args.scratch_d_path), strict=False)

**Comment by LeslieZhoa** [comment]
self.args.scratch_d_path is here https://github.com/LeslieZhoa/GFPGAN-1024/releases/download/untagged-7fadd91b517da1810e55/d.pth

**Comment by luser350** [comment]
@LeslieZhoa page not found. How much later as this issue is 1 month and 8 days old?

**Comment by ningbende** [comment]
> self.args.scratch_d_path is here https://github.com/LeslieZhoa/GFPGAN-1024/releases/download/untagged-7fadd91b517da1810e55/d.pth, I will fix the link later

hi LelieZhoa, still not work, would you please fix this link

**Comment by LeslieZhoa** [comment]
fix it, https://github.com/LeslieZhoa/GFPGAN-1024/releases/download/v0.1/d.pth
